FROM node:14 as build
WORKDIR /usr/local/app
COPY empleado/package*.json ./ 
ENV PORT=5001
RUN npm install
COPY empleado/ empleado/
COPY database/  database/
EXPOSE 5001
CMD ["node", "empleado/index.js"]