- hosts: backend
  become: yes
  tasks:
    - name: Install Python
      package:
        name: "python3"
        state: present

    - name: Install Docker sdk for python
      pip:
        name: docker

    - name: Start Docker service
      service:
        name: "docker"
        state: started    